[profile]
scenario = "fraud"
time = 2021-12-16T13:13:26.590661
user = "test user"

[choices."Question number 0"]
first = "System_B"
second = "System_E"

[choices."Question number 1"]
first = "System_B"
second = "System_D"

[choices."Question number 2"]
first = "System_B"
second = "System_F"

[choices."Question number 3"]
first = "System_B"
second = "System_A"

[choices."Question number 4"]
first = "System_B"
second = "System_C"

[result.System_B]
spec = "dummyclassifier_positive"

[result.System_B.attr]
fp = 9411
fn = 0
fp_cvar = 5.396039603960396
revenue = 0
eo_disadvantage_rate = 0
