steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-f',
           'frontend.Dockerfile',
           '-t', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/frontend', 
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-f',
           'backend.Dockerfile',
           '-t', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/backend', 
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/backend']

