steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-f',
           'backend.Dockerfile',
           '-t', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/backend', 
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-f',
           'frontend.Dockerfile',
           '-t', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/frontend', 
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/aicontrolpanel/backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud',
          'compute',
          'ssh', 
          '--zone',
          'australia-southeast1-b',
          'lb@aicontrolpaneldemo',  
          '--project', 
          'ongoing-236000', 
          '--command',
          'cd /home/app/ai-impact-control-panel && git pull && source source_on_vm.sh']
timeout: 1200s

