# Copyright 2021-2022 Gradient Institute Ltd. <info@gradientinstitute.org>

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./scenarios/:/app/scenarios
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
  db:
    image: "redis"
    command: 'redis-server --save "" --appendonly no'
