version: '3.8'

services:
  backend:
    image: australia-southeast1-docker.pkg.dev/ongoing-236000/aicontrolpanel/backend
  frontend:
    image: australia-southeast1-docker.pkg.dev/ongoing-236000/aicontrolpanel/frontend
