## EXAMPLE MODEL CONFIG

# if <model>.ranges section is defined, this gives the number of draws
n_models = 36

# These are the metrics to be run on the model outputs. The header names should
# match those defined in metrics_dict defined in score.py
# Range is from edge of unacceptable to optimal
[metrics]
# [metrics.auc]
# name = "Area under the ROC curve"
# range = [0.5, 1.0]
# optimal = "max"
# type = "float"
# [metrics.accuracy]
# name = "Accuracy"
# range = [0.0, 1.0]
# optimal = "max"
# type = "float"
[metrics.fp]
name = "False Positives"
range = [1000, 0]
optimal = "min"
type = "int"
[metrics.fn]
name = "False Negatives"
range = [100, 0]
optimal = "min"
type = "int"
[metrics.fn_cvar10]
name = "False Negative CVaR 10%"
range = [20, 0]
type = "float"
optimal = "min"
[metrics.fp_cvar10]
name = "False Positive CVaR 10%"
range = [100, 0]
type = "float"
optimal = "min"
# [metrics.fnwo]
# name = "People with >=3 FN"
# range = [100, 0]
# optimal = "min"
# type = "int"
# [metrics.fpwo]
# name = "People with >=5 FP"
# cutoff = 5
# range = [1000, 0]
# optimal = "min"
# type = "int"
[metrics.profit]
name = "Net profit"
range = [1000.0, 5000.0]
optimal = "max"
type = "float"

