import React, {useState, useEffect} from 'react';
import axios from 'axios';
import {MainPane} from './Pairwise';
import {IntroPane} from './Intro';
import {ResultPane} from './Result';
import './App.css';
import logo from './logo-dark-small.svg';

let metadata = {

    name: "EzyFraud Pro",
    purpose: "to detect and prevent credit card fraud.",
    operation: "the system analyses credit card transactions coming into the bank, blocking those which it predicts to be fraudulent.  An SMS is then sent to the customer, giving them an opportiunity to confirm the legitimacy of the transaction.",
    actions: {
      allow : "allows the transaction to proceed",
      block : "prevents the transaction from occuring, and sends an sms to the customer asking them to confirm the legitimacy of the transaction. If they confirm, then the system will whitelist the transaction so they can re-attempt it."
    },
    targets: {
      fraudulent: "The transaction is fraudulent, i.e. not being conducted with the informed consent of the customer",
    },
    data: "The system is trained with historical transaction data collected by the bank in the last financial year. Positive labels are assumed for undisputed transactions, negative labels come from fraud investigations",
    decision_rules: "Designers set a threshold for the probability of fraud before the system is deployed. All transactions whose predictions meet or exceed the threshold are blocked.",
    candidates: "Candidate models have been generated by hyperparameter sweeps.",
    objectives: {
      catch_fraud: {
        description: "Prevent as many fraudulent transactions as possible for the sake of the bank and the customers",
      },
      avoid_interference: {
        description: "Minimise the number of legitimate transactions blocked to prevent annoying customers",
      },
      minimise_excessive_interfence: {
        description: "Prevent any customers from experiencing exessive false blockings",
      },
      dont_disadvantage_women: {
        description: "Ensure system doesnt make more errors on women",
      }
    },
  }

function App() {

  // they've read and understood the problem setup
  const [ready, setReady] = useState(false);
  // the metadata for the problem
  const [units, setUnits] = useState<any>(null);
  // the result that comes back at the end
  const [result, setResult] = useState(null);

  // initial request on load
  useEffect(() => {
    let req = "metadata";
    async function fetchData() {
      const result = await axios.get<any>(req);
      setUnits(result.data);
    }
    fetchData();
  }, []
  );
  
  let pane = (<h2>Loading...</h2>);
  if (units != null && ready === false) {
    pane = (<IntroPane metadata={metadata} units={units} onClick={() => {setReady(true)}}/>);
  } else if (units!= null && ready === true && result == null) {
    pane = (<MainPane metadata={metadata} units={units} setResult={setResult} />)
  } else if (units != null && ready === true && result != null) {
    pane = (<ResultPane metadata={metadata} units={units} result={result}/>);
  } 

  return (
    <div className="App container text-gray-200 mx-auto px-8 pt-8 bg-gray-800">
      <div className="grid grid-cols-12 text-center items-center mb-8">
        <img className="col-span-2 h-16" src={logo} alt="Gradient Institute logo" />
        <h1 className="col-span-8 text-3xl">AI Governance Control Panel</h1>
        <div className="col-span-2" />
      </div>
      {pane}
    </div>
  );
}



export default App;
