# Copyright 2021-2022 Gradient Institute Ltd. <info@gradientinstitute.org>

[inaction]
    precision = 100
    fnr = 100
    fnr_difference = 0
    privacy_level = 2

[industry_average]
    precision = 60
    fnr = 50
    fnr_difference = 10
    privacy_level = 2
