name = "Synthetic Test" 
purpose = """not much"""
operation = """none"""
data = """none"""
decision_rules = """."""
candidates = """Candidate models are permutations."""
primary_metric = "Wmin"  # This has to refer to a metric

[actions]
recommend = """."""
  
[targets]
interviewed = """."""
  
[objectives.test]
name = "test the algorithm"
description = "Ensure that candidates shortlisted are suitable."

[metrics.Wmin]
    name = "Inequality of missing out"
    icon = "fairness.png"
    description = """Difference in proportion of women missing out on
    being recommended roles they are suited to compared to the average."""
    captures = ["dont_disadvantage_women"]
    limitations = """Sensitive to bias against interviewing women in historical
    data."""
    more = "more"
    less = "fewer"
    prefix = ""
    suffix = "fewer suitable women than the average per 100 candidates"
    action = "recommends"
    higherIsBetter = false
    decimals = 0
    countable = true

[metrics.Xmin]
    name = "Proportion of suitable candidates missed"
    captures = ["minimise_missing_out"]
    limitations = """False negatives (missed candidates) are difficult to
    capture if the training data is from an existing AI system."""
    icon = "missout.png"
    description = """Proportion of candidates who were suitable for the role
    but were missed by the system."""
    more = "more"
    less = "fewer"
    prefix = ""
    suffix = "candidates per 100 suitable"
    action = "missed"
    higherIsBetter = false
    decimals = 0
    countable = true

[metrics.Ymax]
    name = "Correctly shortlisted candidates"
    icon = "shortlist.png"
    captures = ["shortlist_suitable_candidates"]
    limitations = """Does not consider if the candidates will actually be hired
    for the role, only that they may be interviewed."""
    description = """Number of candidates shortlisted per 100 who are suitable
    for the role."""
    more = "more"
    less = "fewer"
    prefix = ""
    suffix = "candidates per 100 suitable"
    action = "recommend{s}"
    higherIsBetter = true
    decimals = 2
    countable = true

[metrics.Zmin]
    name = "feature use"
    icon = "fairness.png"
    description = """Level of private data used in the training set"""
    captures = ["shortlist_suitable_candidates"]
    limitations = """no actual distinguishing"""
    higherIsBetter = false 
    type = "qualitative"
    
    # the values for the options are 0... n-1 respectively
    # options should include a verb
    options = ["great", "good", "okay", "meh", "ohno"] 

    # for comparison between two systems
    comparison_better = "uses less personal data than" 
    comparison_worse = "uses more personal data than"
    comparison_equal = "uses the same amount of personal data as"
