[intro]
    text = "A long time ago in a galaxy far, far away...."

[metrics.fp]
    name = "False Positives"
    icon = "FP"
    description = "legitimate transaction{s} per month"
    more = "additional"
    less = "fewer"
    prefix = ""
    suffix = "trans / month"
    action = "falsely flag{s}"
    higherIsBetter = false
    decimals = 0

[metrics.fn]
    name = "False Negatives"
    icon = "FN"
    description = "fraudulent transaction{s} per month"
    more = "additional"
    less = "fewer"
    prefix = ""
    suffix = "trans / month"
    action = "overlook{s}"
    higherIsBetter = false
    decimals = 0

[metrics.fn3]
    name = "People with >=3 FN"
    icon = "FNWO"
    description = "customer{s} with 3 or more overlooked fraud transactions"
    more = "additional"
    less = "fewer"
    prefix = ""
    suffix = "person{s}"
    action = "burden{s}"
    higherIsBetter = false
    decimals = 0

[metrics.fp5]
    name = "People with >=5 FP"
    icon = "FPWO"
    description = "customer{s} with 5 or more false flags"
    more = "additional"
    less = "fewer"
    prefix = ""
    suffix = "person{s}"
    action = "burden{s}"
    higherIsBetter = false
    decimals = 0

[metrics.profit]
    name = "Net profit"
    icon = "profit"
    description = "net profit"
    more = "more"
    less = "less"
    prefix = "$"
    suffix = ""
    action = "make{s}"
    higherIsBetter = true
    decimals = 2

[metrics.eqop_f]
    name = "Equal Opportunity Female"
    icon = "FN"
    description = "correctly identified fraudulent transactions proportionally on females"
    more = "more"
    less = "fewer"
    prefix = ""
    suffix = "rate"
    action = "make{s}"
    higherIsBetter = false
    decimals = 2

[metrics.eqop_m]
    name = "Equal Opportunity Male"
    icon = "FN"
    description = "correctly identified fraudulent transactions proportionally on males"
    more = "more"
    less = "fewer"
    prefix = ""
    suffix = "rate"
    action = "make{s}"
    higherIsBetter = false
    decimals = 2
