## Model config for group fairness

## What data to use
data_simulation = "fraud"

# if <model>.ranges section is defined, this gives the number of draws
n_range_draws = 10

# Define a customer ID
customer_id = "customer_id"

# Defines a sensitive attribute
sensitive_attribute = "customer_is_female"

#
# Model metrics
#

[metrics]
# [metrics.auc]
# name = "Area under the ROC curve"
# [metrics.accuracy]
# name = "Accuracy"
[metrics.fp]
name = "False Positives"
[metrics.fn]
name = "False Negatives"
# [metrics.fn_cvar]
# name = "False Negative CVaR 10%"
# alpha = 0.1
[metrics.fp_cvar]
name = "False Positive CVaR 10%"
alpha = 0.1
[metrics.revenue]
name = "Net revenue protected"
# Note - realistically this might require knowledge of the transaction value...
TP = 0
FP = 0
TN = 1
FN = -10

[metrics.eo_disadvantage_rate]
name = "Equal Opportunity Female"

# [metrics.eo_advantage_rate]
# name = "Equal Opportunity Male"


#
# Proper ML models
#

[logistic]
fit_intercept = true
random_state = 666
class_weight = 'balanced'
max_iter = 1000
positive_class_weight = 10.0

[logistic.lists]
# threshold_protected = [0.4, 0.5, 0.6]
# threshold = [0.4, 0.5, 0.6]
threshold_protected = [0.4, 0.5]
threshold = [0.4, 0.5]

# stratify_attribute = "customer_is_female"

[dummyclassifier]
[dummyclassifier.instances.positive]
strategy = "constant"
constant = 1

[dummyclassifier.instances.negative]
strategy = "constant"
constant = 0
